import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Script from "next/script";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <Head>
        <script
          type="text/javascript"
          src="/static/script.js"
          async
          defer
        ></script>
      </Head> */}

      <Script
        type="text/javascript"
        id="hs-script-loader"
        async
        defer
        src="https://unpkg.com/flowbite@1.4.1/dist/flowbite.js"
      />

      <body className={inter.className}>{children}</body>
    </html>
  );
}
